#!/bin/bash

# Navigation guide for C3OPS.io Terraform Infrastructure
# Run this file to see all available documentation and commands

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║     C3OPS.io INFRASTRUCTURE - COMPLETE SETUP GUIDE             ║"
echo "║          Terraform + AWS for c3ops.io Domain                   ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "🎯 START HERE:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  First Time? Read This:"
echo "    📄 DEPLOYMENT_COMPLETE.md       ← Complete overview (START HERE)"
echo "    📄 TERRAFORM_QUICK_REFERENCE.md ← Quick commands & examples"
echo ""
echo "2️⃣  Setting Up? Follow These:"
echo "    📄 C3OPS_TERRAFORM_SETUP.md          ← Setup guide (5 phases)"
echo "    📄 TERRAFORM_INFRASTRUCTURE_SUMMARY.md ← Detailed overview"
echo "    📄 TERRAFORM_DEPLOYMENT_GUIDE.md     ← Step-by-step walkthrough"
echo ""
echo "3️⃣  Need Commands? Check:"
echo "    📄 TERRAFORM_QUICK_REFERENCE.md"
echo "    📄 terraform/README.md"
echo ""
echo ""
echo "🚀 QUICK START (5 STEPS):"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Setup AWS Credentials"
echo "  $ bash scripts/setup-aws-credentials.sh"
echo "  $ export AWS_PROFILE=c3ops-io"
echo ""
echo "Step 2: Create ACM Certificate (us-east-1)"
echo "  $ aws acm request-certificate \\"
echo "    --domain-name c3ops.io \\"
echo "    --region us-east-1 \\"
echo "    --profile c3ops-io"
echo ""
echo "Step 3: Configure Terraform"
echo "  $ cd terraform"
echo "  $ cp terraform.tfvars.example terraform.tfvars"
echo "  $ nano terraform.tfvars  # Add certificate_arn"
echo ""
echo "Step 4: Deploy Infrastructure"
echo "  $ terraform init"
echo "  $ terraform plan"
echo "  $ terraform apply"
echo ""
echo "Step 5: Deploy Website"
echo "  $ cd .."
echo "  $ npm run build"
echo "  $ ./scripts/terraform.sh deploy-web"
echo ""
echo ""
echo "📚 DOCUMENTATION FILES:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Overview & Planning:"
echo "  • DEPLOYMENT_COMPLETE.md           (~5,000 words) ⭐ START HERE"
echo "  • TERRAFORM_INFRASTRUCTURE_SUMMARY.md (~4,000 words)"
echo "  • FILE_INVENTORY.md                (Complete file list)"
echo ""
echo "📖 Setup & Deployment:"
echo "  • C3OPS_TERRAFORM_SETUP.md        (~4,500 words)"
echo "  • TERRAFORM_DEPLOYMENT_GUIDE.md   (~3,500 words)"
echo "  • terraform/README.md             (~2,500 words)"
echo ""
echo "⚡ Quick Reference:"
echo "  • TERRAFORM_QUICK_REFERENCE.md    (~1,500 words)"
echo ""
echo ""
echo "🛠️ MANAGEMENT COMMANDS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Using the Management Script:"
echo "  ./scripts/terraform.sh [command]"
echo ""
echo "Commands:"
echo "  init            - Initialize Terraform"
echo "  validate        - Validate configuration"
echo "  plan            - Plan infrastructure"
echo "  apply           - Deploy infrastructure"
echo "  deploy-web      - Build + deploy + invalidate"
echo "  destroy         - Destroy infrastructure"
echo "  help            - Show all commands"
echo ""
echo "Using Make:"
echo "  make help       - Show help"
echo "  make tf-init    - Initialize"
echo "  make tf-plan    - Plan"
echo "  make tf-apply   - Apply"
echo "  make deploy-all - Full deployment"
echo ""
echo ""
echo "📁 TERRAFORM CONFIGURATION:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Files in terraform/ directory:"
echo "  ✅ provider.tf              - AWS provider setup"
echo "  ✅ variables.tf             - Input variables"
echo "  ✅ main.tf                  - S3 + CloudFront"
echo "  ✅ api_gateway.tf           - API Gateway"
echo "  ✅ lambda.tf                - Lambda functions"
echo "  ✅ dynamodb.tf              - DynamoDB"
echo "  ✅ route53.tf               - DNS records"
echo "  ✅ outputs.tf               - Output values"
echo "  ✅ terraform.tfvars.example - Example config"
echo "  ✅ README.md                - Terraform docs"
echo "  ✅ setup.sh                 - Setup script"
echo "  ✅ .gitignore               - Git ignore rules"
echo ""
echo ""
echo "🔐 AWS CREDENTIALS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Account ID:      318095823459"
echo "Region:          ap-south-2"
echo "IAM User:        svc-c3ops.io"
echo ""
echo "⚠️  IMPORTANT:"
echo "  ✋ Credentials are EXPOSED - ROTATE THEM IMMEDIATELY"
echo "  ✋ Read security section in DEPLOYMENT_COMPLETE.md"
echo "  ✋ Enable MFA on AWS account"
echo "  ✋ Never commit credentials to Git"
echo ""
echo ""
echo "🎯 WHAT WILL BE DEPLOYED:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Infrastructure Resources (19 total):"
echo "  ✅ 2 S3 Buckets              (Website + Redirect)"
echo "  ✅ 2 CloudFront Distributions (Primary + Redirect)"
echo "  ✅ 1 HTTP API Gateway        (REST API)"
echo "  ✅ 3 Lambda Functions        (Health, Demo, Typeform)"
echo "  ✅ 1 DynamoDB Table          (Submissions)"
echo "  ✅ 4 Route53 Records         (DNS)"
echo "  ✅ 3 IAM Roles/Policies      (Security)"
echo "  ✅ 3 CloudWatch Components   (Logging/Monitoring)"
echo ""
echo "Features:"
echo "  ✅ HTTPS/TLS Encryption"
echo "  ✅ Global CDN (CloudFront)"
echo "  ✅ Auto-scaling API"
echo "  ✅ Database with PITR"
echo "  ✅ Health monitoring"
echo "  ✅ Domain redirect (c3ops.io → c3ops.io)"
echo "  ✅ Audit logging"
echo "  ✅ Cost optimization"
echo ""
echo ""
echo "📊 INFRASTRUCTURE TOPOLOGY:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "                          Route53 (DNS)"
echo "                              ↓"
echo "          ┌───────────────────┼───────────────────┐"
echo "          ↓                   ↓                   ↓"
echo "    c3ops.io            www.c3ops.io        api.c3ops.io"
echo "          ↓                   ↓                   ↓"
echo "    CloudFront ─────────── S3 Bucket        API Gateway"
echo "    (Primary)                                    ↓"
echo "                                          Lambda Functions"
echo "                                                  ↓"
echo "                                              DynamoDB"
echo ""
echo "                    c3ops.io (Redirect)"
echo "                          ↓"
echo "                  CloudFront → 301 → c3ops.io"
echo ""
echo ""
echo "💰 ESTIMATED COSTS:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Monthly estimate (production usage):"
echo "  CloudFront:   \$10-50   (CDN data transfer)"
echo "  S3:           \$0.50-5  (Storage)"
echo "  API Gateway:  \$5-20    (API requests)"
echo "  Lambda:       \$0.20-5  (Execution time)"
echo "  DynamoDB:     \$0-25    (On-demand pricing)"
echo "  Route53:      \$0.50    (DNS)"
echo "  ───────────────────────────────"
echo "  TOTAL:        ~\$20-100/month"
echo ""
echo ""
echo "📞 SUPPORT & HELP:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Documentation:"
echo "  • Read DEPLOYMENT_COMPLETE.md for complete overview"
echo "  • Check TERRAFORM_QUICK_REFERENCE.md for commands"
echo "  • See FILE_INVENTORY.md for file descriptions"
echo ""
echo "External Resources:"
echo "  • Terraform: https://www.terraform.io/docs"
echo "  • AWS: https://docs.aws.amazon.com/"
echo "  • C3OPS: info@c3ops.io"
echo ""
echo ""
echo "✅ SETUP CHECKLIST:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Before deploying:"
echo "  [ ] Read DEPLOYMENT_COMPLETE.md"
echo "  [ ] Run scripts/setup-aws-credentials.sh"
echo "  [ ] Rotate AWS credentials"
echo "  [ ] Create ACM certificate"
echo "  [ ] Copy terraform.tfvars.example → terraform.tfvars"
echo "  [ ] Update certificate_arn in terraform.tfvars"
echo "  [ ] Run terraform init"
echo "  [ ] Review terraform plan"
echo "  [ ] Run terraform apply"
echo "  [ ] Build and deploy website"
echo "  [ ] Verify endpoints work"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Ready to deploy? Start with DEPLOYMENT_COMPLETE.md! 🚀       ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
